services:
  nginx:
    image: nginx:alpine
    container_name: saas_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - client_saas

  client_saas:
    build: .
    # image: saas:prod
    container_name: saas_app_client
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./data/sqlite:/app/data

      # - ./data/sqlite:/app

  prom_server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
